adminUser:
  password: local:jxgitops/adminUser:password
  username: admin
enableDocker: false
gitProvider: github
gpg:
  passphrase: local:jxgitops/gpg:passphrase
pipelineUser:
  github:
    host: github.com
    token: local:jxgitops/pipelineUser-github:token
    username: sajid2045
prow:
  hmacToken: local:jxgitops/prow:hmacToken
