cluster:
  domain: ""
  namespaceSubDomain: ""
  name: ""
  projectID: ""
  serverUrl: ""
  zone: ""
  tls: false

gitops:
  gitKind: github
  server: https://github.com
  owner: sajid2045

  dev:
    repo: environment-simple-tekton
    owner: sajid2045
    server: ""
  staging:
    repo: environment-jstrachan-ad1-staging
    owner: ""
    server: ""
  production:
    repo: environment-jstrachan-ad1-production
    owner: ""
    server: ""

controllerbuild:
  enabled: true
controllerworkflow:
  enabled: false
jenkins:
  enabled: false
jenkins-x-platform:
  chartmuseum:
    enabled: true
    env:
      open:
        AUTH_ANONYMOUS_GET: true
        DISABLE_API: false
#        STORAGE: google
#        STORAGE_GOOGLE_BUCKET: chartmuseum.jenkins-x.io
#        STORAGE_GOOGLE_PREFIX: charts
#    gcp:
#      secret:
#        enabled: true
#        key: gcs-chartmuseum.key.json
#        name: gcs-jenkinsx-chartmuseum
    image:
      tag: v0.7.1
  controllerbuild:
    enabled: true
  dockerRegistry: gcr.io
  jenkins:
    Agent:
      PodTemplates:
        Go:
          Containers:
            Go:
              Image: jenkinsxio/builder-go:latest
        Maven:
          Containers:
            Maven:
              Image: jenkinsxio/builder-maven:latest
          volumes:
          - mountPath: /root/.m2/
            secretName: jenkins-maven-settings
            type: Secret
          - mountPath: /home/jenkins/.docker
            secretName: jenkins-docker-cfg
            type: Secret
        Nodejs:
          Containers:
            Nodejs:
              Image: jenkinsxio/builder-nodejs:latest
  monocular:
    api:
      livenessProbe:
        initialDelaySeconds: 1000
  nexus:
    persistence:
      size: 100Gi
  postinstalljob:
    enabled: "true"


JenkinsXGitHub:
  username: "{{ .Parameters.pipelineUser.github.username }}"
  password: "{{ .Parameters.pipelineUser.github.token }}"
